/**
 * AWS Services data — used by the 3D Network Visualizer and Architecture Simulator.
 * Prices are illustrative only and may be outdated.
 */

export type ServiceCategory =
  | "compute"
  | "storage"
  | "database"
  | "network"
  | "security"
  | "messaging"
  | "analytics"
  | "ml"
  | "cdn";

export interface AwsService {
  id: string;
  name: string;
  shortName: string;
  category: ServiceCategory;
  description: string;
  // Illustrative pricing (for simulator display)
  pricingModel: string;
  costPerMonth: number; // baseline assumption
  latencyMs: number; // typical latency
  reliability: number; // 0-100 (SLA-ish)
  securityLevel: number; // 0-100
  // 3D position preset for the visualizer (x, y, z)
  position: [number, number, number];
  color: string;
  emoji: string;
  alternatives?: string[]; // service IDs for swap
}

export const awsServices: AwsService[] = [
  // Compute
  {
    id: "ec2",
    name: "Amazon EC2",
    shortName: "EC2",
    category: "compute",
    description: "Virtual servers in the cloud",
    pricingModel: "Per hour",
    costPerMonth: 73,
    latencyMs: 5,
    reliability: 99.99,
    securityLevel: 85,
    position: [-3, 1, 0],
    color: "#ff9900",
    emoji: "🖥️",
    alternatives: ["lambda", "fargate", "ecs"],
  },
  {
    id: "lambda",
    name: "AWS Lambda",
    shortName: "Lambda",
    category: "compute",
    description: "Run code without provisioning servers",
    pricingModel: "Per invocation",
    costPerMonth: 12,
    latencyMs: 100,
    reliability: 99.95,
    securityLevel: 90,
    position: [-3, -1, 0],
    color: "#ff9900",
    emoji: "λ",
    alternatives: ["ec2", "fargate"],
  },
  {
    id: "fargate",
    name: "AWS Fargate",
    shortName: "Fargate",
    category: "compute",
    description: "Serverless compute for containers",
    pricingModel: "Per vCPU/GB-hour",
    costPerMonth: 55,
    latencyMs: 10,
    reliability: 99.99,
    securityLevel: 90,
    position: [-3, 0, 2],
    color: "#ff9900",
    emoji: "📦",
    alternatives: ["ec2", "ecs", "lambda"],
  },
  {
    id: "ecs",
    name: "Amazon ECS",
    shortName: "ECS",
    category: "compute",
    description: "Container orchestration service",
    pricingModel: "Per task",
    costPerMonth: 60,
    latencyMs: 8,
    reliability: 99.99,
    securityLevel: 88,
    position: [-3, -2, 1],
    color: "#ff9900",
    emoji: "🐳",
    alternatives: ["fargate", "eks"],
  },
  {
    id: "eks",
    name: "Amazon EKS",
    shortName: "EKS",
    category: "compute",
    description: "Managed Kubernetes service",
    pricingModel: "$0.10/cluster/hour + nodes",
    costPerMonth: 150,
    latencyMs: 8,
    reliability: 99.95,
    securityLevel: 88,
    position: [-3, 2, 1],
    color: "#ff9900",
    emoji: "☸️",
    alternatives: ["ecs", "fargate"],
  },

  // Storage
  {
    id: "s3",
    name: "Amazon S3",
    shortName: "S3",
    category: "storage",
    description: "Object storage — 11 9s of durability",
    pricingModel: "Per GB-month",
    costPerMonth: 23,
    latencyMs: 50,
    reliability: 99.999999999,
    securityLevel: 95,
    position: [3, 1, 0],
    color: "#569a31",
    emoji: "🪣",
    alternatives: ["efs", "ebs"],
  },
  {
    id: "ebs",
    name: "Amazon EBS",
    shortName: "EBS",
    category: "storage",
    description: "Block storage for EC2",
    pricingModel: "Per GB-month",
    costPerMonth: 80,
    latencyMs: 1,
    reliability: 99.99,
    securityLevel: 90,
    position: [3, -1, 0],
    color: "#569a31",
    emoji: "💾",
    alternatives: ["efs", "s3"],
  },
  {
    id: "efs",
    name: "Amazon EFS",
    shortName: "EFS",
    category: "storage",
    description: "Managed shared file system (NFS)",
    pricingModel: "Per GB-month",
    costPerMonth: 300,
    latencyMs: 3,
    reliability: 99.99,
    securityLevel: 92,
    position: [3, 2, 0],
    color: "#569a31",
    emoji: "📁",
    alternatives: ["s3", "fsx"],
  },
  {
    id: "fsx",
    name: "Amazon FSx",
    shortName: "FSx",
    category: "storage",
    description: "Managed file systems (Windows/Lustre)",
    pricingModel: "Per GB-month",
    costPerMonth: 400,
    latencyMs: 2,
    reliability: 99.99,
    securityLevel: 92,
    position: [3, -2, 0],
    color: "#569a31",
    emoji: "📂",
    alternatives: ["efs", "s3"],
  },

  // Database
  {
    id: "rds",
    name: "Amazon RDS",
    shortName: "RDS",
    category: "database",
    description: "Managed relational databases",
    pricingModel: "Per instance-hour",
    costPerMonth: 120,
    latencyMs: 5,
    reliability: 99.95,
    securityLevel: 92,
    position: [0, 2, -3],
    color: "#3b48cc",
    emoji: "🗄️",
    alternatives: ["aurora", "dynamodb"],
  },
  {
    id: "aurora",
    name: "Amazon Aurora",
    shortName: "Aurora",
    category: "database",
    description: "MySQL/Postgres-compatible DB with cloud-native performance",
    pricingModel: "Per instance-hour",
    costPerMonth: 200,
    latencyMs: 3,
    reliability: 99.99,
    securityLevel: 94,
    position: [0, 1, -3],
    color: "#3b48cc",
    emoji: "🌌",
    alternatives: ["rds", "dynamodb"],
  },
  {
    id: "dynamodb",
    name: "Amazon DynamoDB",
    shortName: "DynamoDB",
    category: "database",
    description: "Serverless NoSQL key-value store",
    pricingModel: "Per request + storage",
    costPerMonth: 80,
    latencyMs: 2,
    reliability: 99.999,
    securityLevel: 93,
    position: [0, 0, -3],
    color: "#3b48cc",
    emoji: "⚡",
    alternatives: ["rds", "aurora"],
  },
  {
    id: "elasticache",
    name: "ElastiCache",
    shortName: "ElastiCache",
    category: "database",
    description: "In-memory caching (Redis/Memcached)",
    pricingModel: "Per node-hour",
    costPerMonth: 75,
    latencyMs: 0.5,
    reliability: 99.9,
    securityLevel: 88,
    position: [0, -1, -3],
    color: "#3b48cc",
    emoji: "⚡",
  },
  {
    id: "redshift",
    name: "Redshift",
    shortName: "Redshift",
    category: "analytics",
    description: "Columnar data warehouse",
    pricingModel: "Per node-hour",
    costPerMonth: 720,
    latencyMs: 50,
    reliability: 99.9,
    securityLevel: 92,
    position: [0, -2, -3],
    color: "#3b48cc",
    emoji: "📊",
  },

  // Network
  {
    id: "alb",
    name: "Application Load Balancer",
    shortName: "ALB",
    category: "network",
    description: "Layer-7 load balancer with content-based routing",
    pricingModel: "$0.0225/ALB-hour + LCU",
    costPerMonth: 22,
    latencyMs: 1,
    reliability: 99.99,
    securityLevel: 90,
    position: [0, 3, 0],
    color: "#cf1126",
    emoji: "⚖️",
    alternatives: ["nlb", "clb"],
  },
  {
    id: "nlb",
    name: "Network Load Balancer",
    shortName: "NLB",
    category: "network",
    description: "Layer-4 LB for millions of connections",
    pricingModel: "$0.0225/NLB-hour + LCU",
    costPerMonth: 22,
    latencyMs: 0.1,
    reliability: 99.99,
    securityLevel: 92,
    position: [0, 3, 2],
    color: "#cf1126",
    emoji: "🔌",
    alternatives: ["alb"],
  },
  {
    id: "route53",
    name: "Route 53",
    shortName: "Route 53",
    category: "network",
    description: "Authoritative DNS + health checks",
    pricingModel: "$0.50/hosted zone",
    costPerMonth: 5,
    latencyMs: 20,
    reliability: 100,
    securityLevel: 95,
    position: [0, 4, 0],
    color: "#cf1126",
    emoji: "🌐",
  },
  {
    id: "vpc",
    name: "VPC",
    shortName: "VPC",
    category: "network",
    description: "Isolated virtual network",
    pricingModel: "Free (NAT/endpoint hours billed)",
    costPerMonth: 35,
    latencyMs: 0,
    reliability: 99.99,
    securityLevel: 98,
    position: [-2, 3, 0],
    color: "#cf1126",
    emoji: "🏙️",
  },
  {
    id: "apigateway",
    name: "API Gateway",
    shortName: "API GW",
    category: "network",
    description: "Managed REST/HTTP/WebSocket API frontend",
    pricingModel: "$3.50/M requests",
    costPerMonth: 35,
    latencyMs: 30,
    reliability: 99.95,
    securityLevel: 92,
    position: [2, 3, 0],
    color: "#cf1126",
    emoji: "🚪",
    alternatives: ["alb"],
  },
  {
    id: "cloudfront",
    name: "CloudFront",
    shortName: "CloudFront",
    category: "cdn",
    description: "Global CDN with edge locations",
    pricingModel: "Per GB transferred",
    costPerMonth: 85,
    latencyMs: 15,
    reliability: 99.99,
    securityLevel: 94,
    position: [0, 3, 3],
    color: "#cf1126",
    emoji: "🌍",
  },

  // Messaging
  {
    id: "sqs",
    name: "Amazon SQS",
    shortName: "SQS",
    category: "messaging",
    description: "Managed message queues",
    pricingModel: "Per request",
    costPerMonth: 15,
    latencyMs: 10,
    reliability: 99.9,
    securityLevel: 92,
    position: [3, 0, 3],
    color: "#e7157b",
    emoji: "📬",
    alternatives: ["sns", "eventbridge"],
  },
  {
    id: "sns",
    name: "Amazon SNS",
    shortName: "SNS",
    category: "messaging",
    description: "Pub/sub messaging fanout",
    pricingModel: "Per request",
    costPerMonth: 8,
    latencyMs: 50,
    reliability: 99.9,
    securityLevel: 92,
    position: [3, 1, 3],
    color: "#e7157b",
    emoji: "📢",
    alternatives: ["sqs", "eventbridge"],
  },
  {
    id: "eventbridge",
    name: "EventBridge",
    shortName: "EventBridge",
    category: "messaging",
    description: "Serverless event bus",
    pricingModel: "Per event",
    costPerMonth: 10,
    latencyMs: 50,
    reliability: 99.99,
    securityLevel: 92,
    position: [3, -1, 3],
    color: "#e7157b",
    emoji: "🎯",
    alternatives: ["sns", "sqs"],
  },
  {
    id: "kinesis",
    name: "Kinesis",
    shortName: "Kinesis",
    category: "analytics",
    description: "Real-time streaming",
    pricingModel: "Per shard-hour",
    costPerMonth: 90,
    latencyMs: 100,
    reliability: 99.9,
    securityLevel: 90,
    position: [3, -2, 3],
    color: "#e7157b",
    emoji: "🌊",
    alternatives: ["kafka", "eventbridge"],
  },

  // Security
  {
    id: "iam",
    name: "IAM",
    shortName: "IAM",
    category: "security",
    description: "Identity and Access Management",
    pricingModel: "Free",
    costPerMonth: 0,
    latencyMs: 10,
    reliability: 100,
    securityLevel: 100,
    position: [-2, 4, -2],
    color: "#d93732",
    emoji: "🔐",
  },
  {
    id: "kms",
    name: "AWS KMS",
    shortName: "KMS",
    category: "security",
    description: "Managed encryption key service",
    pricingModel: "$1/key/month",
    costPerMonth: 1,
    latencyMs: 5,
    reliability: 99.999,
    securityLevel: 100,
    position: [2, 4, -2],
    color: "#d93732",
    emoji: "🔑",
  },
  {
    id: "waf",
    name: "AWS WAF",
    shortName: "WAF",
    category: "security",
    description: "Web application firewall",
    pricingModel: "$5/web ACL + request fees",
    costPerMonth: 15,
    latencyMs: 2,
    reliability: 99.95,
    securityLevel: 95,
    position: [0, 5, 0],
    color: "#d93732",
    emoji: "🛡️",
  },
];

export const getService = (id: string) => awsServices.find((s) => s.id === id);

// Connection edges for the default reference architecture
export const defaultArchitectureEdges: Array<[string, string, number]> = [
  // [from, to, traffic-weight]
  ["route53", "cloudfront", 5],
  ["cloudfront", "alb", 5],
  ["alb", "ec2", 3],
  ["alb", "fargate", 2],
  ["apigateway", "lambda", 4],
  ["lambda", "dynamodb", 3],
  ["lambda", "sqs", 2],
  ["ec2", "rds", 3],
  ["ec2", "s3", 2],
  ["ec2", "elasticache", 2],
  ["fargate", "aurora", 2],
  ["sqs", "lambda", 2],
  ["sns", "sqs", 2],
  ["eventbridge", "lambda", 2],
  ["kinesis", "lambda", 2],
  ["waf", "cloudfront", 1],
  ["iam", "ec2", 1],
  ["iam", "lambda", 1],
  ["kms", "s3", 1],
  ["kms", "rds", 1],
];
